include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude: [ "lib/firebase_options.dart", "**/*.g.dart" ]

linter:
  rules:
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    cascade_invocations: false
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_print: true
    eol_at_end_of_file: true
    hash_and_equals: true
    prefer_final_in_for_each: true
    prefer_foreach: true
    prefer_inlined_adds: true
    use_key_in_widget_constructors: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    prefer_function_declarations_over_variables: true
    prefer_adjacent_string_concatenation: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_single_quotes: true
    missing_whitespace_between_adjacent_strings: true
    no_runtimeType_toString: true
    test_types_in_equals: true
    unnecessary_await_in_return: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    comment_references: true
    join_return_with_assignment: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    package_api_docs: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_relative_imports: true
    use_string_buffers: true
    use_super_parameters: true
