name: petit_editor
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  flutter_hooks: ^0.18.6
  get_it: ^7.3.0
  google_fonts: ^4.0.3
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  go_router: ^6.5.8
  gap: ^3.0.0
  macos_ui: ^1.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  go_router_builder: ^1.2.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
