name: petit_editor
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  zug:
  google_fonts: ^4.0.3
  go_router: ^7.0.1
  gap: ^3.0.0
  fluent_ui: ^4.6.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  collection: ^1.17.1
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.0.1
  build_runner:
  mobx_codegen: ^2.3.0
  dart_flutter_team_lints:

flutter:
  uses-material-design: true

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch --delete-conflicting-outputs
