name: petit_editor
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  google_fonts: ^4.0.3
  go_router: ^6.5.8
  gap: ^3.0.0
  fluent_ui: ^4.5.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^1.2.2
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3
  freezed: ^2.3.3
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch --delete-conflicting-outputs
