name: petit_workspace

environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  melos: ^3.0.1
  dart_flutter_team_lints: ^1.0.0

scripts:
  build:
    apps:
      editor: (cd apps/editor && rps build)
      all: rps build apps editor
    packages:
      zug: (cd packages/zug && rps build)
      all: rps build packages zug
    all: rps build packages all && rps build apps all
