name: petit_workspace
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  melos: ^3.0.1

scripts:
  build:
    apps:
      editor: (cd apps/editor && rps build)
      all: |
        rps build apps editor
    all: |
      rps build apps all
  watch:
    editor: (cd apps/editor && rps watch)
    all: |
      rps watch editor
