name: petit_zug
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  flutter_hooks: ^0.18.6
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

flutter:

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
